name: Compile C++ to HTML5 Website
on: [push]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Emscripten (Web Compiler)
      uses: mymindstorm/setup-emsdk@v14

    - name: Download and Build Raylib for Web
      run: |
        git clone --depth 1 https://github.com
        cd raylib/src
        make PLATFORM=PLATFORM_WEB
        cd ../..

    - name: Compile Folder into Website
      run: |
        emcc *.cpp -o index.html -Os -Wall -I./raylib/src ./raylib/src/libraylib.a \
        -s USE_GLFW=3 -s ASYNCIFY -s TOTAL_MEMORY=67108864 \
        -DPLATFORM_WEB

    - name: Deploy Game to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .
        branch: gh-pages
