name: Compile C++ EXE with Raylib
on: [push]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSYS2 and Install Raylib
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-raylib

    - name: Compile C++ Folder
      run: |
        g++ *.cpp -o game.exe -lraylib -lopengl32 -lgdi32 -lwinmm

    - name: Upload Finished EXE
      uses: actions/upload-artifact@v4
      with:
        name: my-windows-game
        path: game.exe
