name: Compile C++ to HTML5 Website
on: [push]

permissions:
  contents: write

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Emscripten (Web Compiler)
      uses: mymindstorm/setup-emsdk@v14

    - name: Fetch Raylib Web-Assembly Binaries
      run: |
        curl -sL https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_webassembly.zip -o raylib.zip
        unzip raylib.zip
        mv raylib-5.0_webassembly/lib/libraylib.a .
        mv raylib-5.0_webassembly/include/*.h .

    - name: Compile Folder into Website
      run: |
        emcc *.cpp -o index.html libraylib.a -Os -Wall \
        -s USE_GLFW=3 -s ASYNCIFY -s TOTAL_MEMORY=67108864 \
        -s GL_ENABLE_GET_PROC_ADDRESS=1 -DPLATFORM_WEB

    - name: Deploy Game to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .
        branch: gh-pages
